version: '3'

services:
  hub:
    image: selenium/hub:latest
    ports:
      - "4444:4444"
    networks:
      - selenium-grid
  firefox:
    image: selenium/node-firefox:latest
    environment:
      - NODE_MAX_INSTANCES=2
      - NODE_MAX_SESSION=2
      - HUB_PORT_4444_TCP_ADDR=hub
      - HUB_PORT_4444_TCP_PORT=4444
    volumes:
      - /dev/shm:/dev/shm
    networks:
      - selenium-grid
    depends_on:
      - hub
  chrome:
    image: selenium/node-chrome:latest
    environment:
      - NODE_MAX_INSTANCES=2
      - NODE_MAX_SESSION=2
      - HUB_PORT_4444_TCP_ADDR=hub
      - HUB_PORT_4444_TCP_PORT=4444
    volumes:
      - /dev/shm:/dev/shm
    networks:
      - selenium-grid
    depends_on:
      - hub

  e2e:
    build:
      context: ..
      dockerfile: ./e2eTests/Dockerfile
    environment:
      - AWS_SECRET_ACCESS_KEY
      - AWS_ACCESS_KEY_ID
    depends_on:
      - hub 
      - ayespy_report
    networks:
      - selenium-grid

  ayespy_report:
    image: nginx
    volumes:
      - ./testSite:/usr/share/nginx/html
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
       - "4000:4000"
    environment:
      - NGINX_PORT=4000
    networks:
      - selenium-grid

networks:
  selenium-grid:
